routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('index');

Route::get('/upload', 'HomeController@uploadGet')->name('upload.get');
Route::post('/upload', 'HomeController@uploadPost')->name('upload.post');

Route::group(['middleware' => 'auth.basic.once'], function () {
    Route::resource('/files', 'UploadedFilesController')->only(['index','destroy']);
});

app/Models/UploadedImage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UploadedImage extends Model
{
    protected $fillable = [
        'mimeType',
        'originalName',
        'size',

        'path',

        'path_s',
        'path_m',
    ];

    public function getNameAttribute()
    {
        $parts = explode('/', $this->path);

        return $parts[count($parts) -  1];
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\{
    DB, Storage
};


use App\Events\ImageUploadedEvent;

use App\Models\UploadedImage;
use App\Http\Requests\UploadImagesRequest;
/**
 * Class HomeController
 * @package App\Http\Controllers
 */
class HomeController extends Controller
{

    public function index()
    {
        return view('index');
    }

    public function uploadGet()
    {
        return view('upload');
    }

    public function uploadPost(UploadImagesRequest $request)
    {
        $data = $request->validated();

        $filesCount = count($data['files']);

        DB::beginTransaction();

        foreach($data['files'] as $file) {

            $path = Storage::putFile('images', $file);

            $uploadedImage = UploadedImage::create([
                'mimeType' => $file->getClientMimeType(),
                'originalName' => $file->getClientOriginalName(),
                'size' => Storage::size($path),
                'path' => $path
            ]);

            event(new ImageUploadedEvent($uploadedImage));
        }

        DB::commit();

        return redirect()
            ->back()
            ->with('success', "Successfully uploaded ${filesCount} files!");
    }
}

app/Http/Controllers/UploadedFilesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Models\UploadedImage;

class UploadedFilesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        $items = UploadedImage::paginate(20);

        return view('files.list', [
            'items' => $items
        ]);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  UploadedImage $file
     * @return \Illuminate\Http\Response
     */
    public function destroy(UploadedImage $file)
    {
        Storage::disk('local')->delete($file->path);

        $diskPublic = Storage::disk('public');

        $diskPublic->delete($file->path_m);
        $diskPublic->delete($file->path_s);

        $file->delete();
    }
}

resources/views/files/edit.blade.php
@extends('layouts.app')

@section('content')

  <div class="row">

  <div class="col-md-6 offset-md-3">
        <h2>edit user {{ $item->email }}</h2>
    </div>

  </div>

<br/>

@if ($errors)
  @foreach ($errors->all() as $error)
      <div>{{ $error }}</div>
  @endforeach
@endif


<form method="POST" action="{{ $action }}">

  {{ csrf_field() }}
  {!! method_field($method) !!}

  <input type="hidden" name="id" value="{{ $item['id'] or null }}">

  <div class="row">
    <div class="col-md-3 offset-md-3">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">name</span>
        </div>
        <input type="text" class="form-control" value="{{ $item->name }}" name="name">
      </div>
    </div>
    <div class="col-md-3">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">role</span>
        </div>
        <input type="text" class="form-control" readonly="readonly" value="{{ $item->roles()->first()->name }}">        
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 offset-md-3">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">telegram id</span>
        </div>
        <input type="text" class="form-control" readonly="readonly" value="{{ $item->telegram_id }}" name="email">


      </div>
    </div>
    <div class="col-md-3">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">email</span>
        </div>
        <input type="text" class="form-control" readonly="readonly" value="{{ $item->email }}">
      </div>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6 offset-md-3">
      <label class="control-label" for="sub_id_name">
          select sub id: <span class="text-danger"> </span>
      </label>
      <br>
      <select name="sub_ids_ids[]" id="sub_ids_ids" multiple>
        @foreach($item->subIds as $subId)
          <option selected="selected" value="{{ $subId->id }}">{{ $subId->name }}</option>
        @endforeach
      </select>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6 offset-md-3">
      <button type="submit" class="btn btn-block btn-success">update</button>
    </div>
  </div>


</form>


@endsection


@push('style')
 
@endpush

@push('scripts')
  
  <script type="text/javascript">

    function subIdsSelect2($select, route) {

      let sub_ids_ids = [];

      $select.find('option').each(function(){
        sub_ids_ids.push($(this).val());
      });

      $select.on('select2:select', function (e) {
        var data = e.params.data;
        sub_ids_ids.push(data.id);
      });

      // console.log('existing users ids:', sub_ids_ids);

      $select.select2({
        placeholder: "select sub id",
        minimumInputLength: 2,
        ajax: {
          url: route,
          dataType: 'json',
          data: function (params) {
            return {
              query: params.term,
              page: params.page,
              sub_ids_ids: sub_ids_ids,
              _token: '{{ csrf_token() }}'
            };
          },
          processResults: function (data, params) {
            return {
              results: data.results,
              pagination: {
                more: data.more
              }
            };
          },
          cache: false
        }
      });
    }

    $(document).ready(function() {

        console.log('document ready');

        subIdsSelect2($('#sub_ids_ids'), '{{ route('admin.postback.sub-ids.search') }}');
    });
  </script>
@endpush

resources/views/files/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">

	<div class="col-md-6">
		<h2>Files</h2>
	</div>
</div>

<br>

<table class="table table-bordered">
	<thead>
		<tr class="text-center">

			<th scope="col">id</th>
            <th scope="col">date</th>

			<th scope="col">original name</th>
			<th scope="col">name</th>
			<th scope="col">size</th>
            <th scope="col">links</th>


			<th scope="col">actions</th>

		</tr>
	</thead>
	<tbody>

		@foreach($items as $file)

		<tr class="text-center">

			<td class="align-middle">
				{{ $file->id }}
			</td>

            <td class="align-middle">
                {{ $file->created_at }}
            </td>

			<td class="align-middle">
				{{ $file->originalName }}
			</td>
			<td class="align-middle">
				{{ $file->name }}
			</td>
            <td class="align-middle">
                {{ $file->size }}
            </td>

            <td class="align-middle">
                @if($file->path_s && $file->path_m)
                    <a target="_blank" href="/storage/{{ $file->path_m }}">medium</a>
                    <br>
                    <a target="_blank" href="/storage/{{ $file->path_s }}">thumb</a>
                @endif
            </td>

			<td class="align-middle" >
                <a style="" data-href="{{ route('files.destroy', $file->id) }}" class="remove-status" data-item-id="{{ $file->id }}">
                    <i class="fa fa-close icon-close text-danger"></i>
                    Remove
                </a>
			</td>
		</tr>

		@endforeach
	</tbody>
</table>


<div class="text-center">
{{--	{!! $items->appends(\Request::except('page'))->render() !!}--}}
</div>

@endsection

@push('scripts')
    <script>

        $(function(){


            function removeItem(url) {

                $.ajax({
                    url: url,
                    method: 'POST',
                    data: {
                        "_token": '{{ csrf_token() }}',
                        "_method": 'DELETE'
                    },
                    success: function (response) {
                        location.reload();
                    },
                    error: function (response) {
                        alert('Ошибка!')
                    }
                });

            }

            $('.remove-status').on('click', function (e) {

                e.preventDefault();

                var self = this;

                var isConfirmed = confirm('Do you confirm removing file?');

                if (!isConfirmed) {
                    return false;
                }

                // alert(isConfirmed);
                removeItem($(self).data('href'));

            });

        });

    </script>
@endpush

resources/views/flash-messages.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif


@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif


@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif


@if ($message = Session::get('info'))
    <div class="alert alert-info alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif


@if ($errors->any())
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        Please check the form below for errors
    </div>
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="jumbotron">
        <h1 class="display-4">Laravel Images Uploader Test Task</h1>
        <p class="lead" style="display: none;">
            This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.
        </p>
        <hr class="my-4">
        <p>
            <ul>
                <li> - Аплоадить можно как по одной картинке, так и пачкой до 10 файлов.</li>

                <li> - Картинки должны ресайзится для 2-ух размеров: большая картинка и миниатюра.</li>


                <li>- Оригинал должен хранится отдельно и никаких ресайзов, кропов
                с ним проводить не надо (кроме изменения названия).- Оригинал должен хранится отдельно и никаких ресайзов, кропов
                с ним проводить не надо (кроме изменения названия).</li>

                <li>- Оригинал хранится в приватном сторейдже, большая картинка и миниатюра в публичном.</li>
                <li>- Для миниатюр создается папка thumbs.</li>

                <li>- Названия оригинала, большой и маленькой картинки совпадают.</li>
                <li>- Поддиректория для картинок должна создаваться автоматически, если таковой нет.</li>
                <li>- Название картинки должно генерироваться</li>

            </ul>

        </p>

        <p class="lead">
            <a class="btn btn-primary btn-lg" href="/index.php/upload" role="button">Learn more</a>
        </p>
    </div>


@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->

    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">

        @include('navbar')

        <main class="py-4 container">

            @include('flash-messages')

            @yield('content')
        </main>
    </div>

    <script src="{{ asset('js/jquery.min.js') }}" ></script>
    @stack('scripts')

</body>
</html>

resources/views/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" href="/index.php/upload">{{ __('Upload') }}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/index.php/files">{{ __('Files') }}</a>
                </li>

{{--                <!-- Authentication Links -->--}}
{{--                @guest--}}
{{--                    <li class="nav-item">--}}
{{--                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>--}}
{{--                    </li>--}}
{{--                    @if (Route::has('register'))--}}
{{--                        <li class="nav-item">--}}
{{--                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>--}}
{{--                        </li>--}}
{{--                    @endif--}}
{{--                @else--}}
{{--                    <li class="nav-item dropdown">--}}
{{--                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>--}}
{{--                            {{ Auth::user()->name }} <span class="caret"></span>--}}
{{--                        </a>--}}

{{--                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">--}}
{{--                            <a class="dropdown-item" href="{{ route('logout') }}"--}}
{{--                               onclick="event.preventDefault();--}}
{{--                                                     document.getElementById('logout-form').submit();">--}}
{{--                                {{ __('Logout') }}--}}
{{--                            </a>--}}

{{--                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">--}}
{{--                                @csrf--}}
{{--                            </form>--}}
{{--                        </div>--}}
{{--                    </li>--}}
{{--                @endguest--}}
            </ul>
        </div>
    </div>
</nav>

resources/views/upload.blade.php
@extends('layouts.app')

@section('content')

    <form action="{{ route('upload.post') }}" method="post" enctype="multipart/form-data">

        @csrf

        <div class="row justify-content-center">

            <div class="col-md-6">

                <h2>Upload Images</h2>

                <br>

                <p>Upload at least one image file below.</p>
                <p>You can add more files by clicking "Add file" button</p>

            </div>

            <div class="col-md-3 text-right">

                <a class="btn btn-primary btn-lg"  id="add-file" role="button">Add file</a>

            </div>
        </div>


        <div class="row justify-content-center">

            <div class="col-md-9" id="file-inputs">
                <input type="file" name="files[0]">
            </div>

        </div>


        <div class="row justify-content-center">
            <div class="form-group col-md-9">
                <br>
                <hr>
                <br>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="form-group col-md-9">
                <button type="submit" class="btn btn-block btn-success">Submit</button>
            </div>
        </div>

    </form>

@endsection


@push('scripts')

    <script type="text/javascript">

        $(document).ready(function(){

            let $btnAddFile = $('#add-file');
            let $fileInputs = $('input[type="file"]');
            let $fileInputsContainer = $('#file-inputs');

            $btnAddFile.on('click', function(){
                $fileInputs = $('input[type="file"]');

                let newInputIndex = $fileInputs.length;

                $fileInputsContainer.append('<br><br>');
                $fileInputsContainer.append('<input type="file" name="files[' + newInputIndex + ']">');

            });

        });

    </script>
@endpush